config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :api_requests
    resources :collections
  end

  resources :settings, only: [:index, :update]

  DynamicRouter.load

end

app/models/api_request.rb
# == Schema Information
#
# Table name: api_requests
#
#  id             :integer          not null, primary key
#  request_method :string
#  request_path   :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  return_json    :json
#  status_code    :integer
#  name           :string           default(""), not null
#  description    :text             default(""), not null
#  project_id     :integer
#  collection_id  :integer
#
# Indexes
#
#  index_api_requests_on_collection_id  (collection_id)
#  index_api_requests_on_project_id     (project_id)
#

require 'mustermann'
class ApiRequest < ApplicationRecord
  belongs_to :project
  belongs_to :collection

  has_many :parameters, dependent: :destroy
  has_many :headers, dependent: :destroy

  accepts_nested_attributes_for :parameters, allow_destroy: true
  accepts_nested_attributes_for :headers, allow_destroy: true

  validates_presence_of :request_method, :request_path, :status_code, :return_json

  after_commit :append_to_routes, on: :create
  after_update :append_to_routes, if: :route_changed?
  before_save :downcase_request_path_and_set_path
  before_save :upcase_request_method
  before_save :delete_request_path_end_slash

  scope :uncollection, -> { where(collection_id: nil) }

  REQUEST_METHOD = %w( get post put patch delete ).freeze
  REQUEST_METHOD.each do |req|
    scope "by_#{req}".to_sym, -> { where(request_method: req.upcase) }
  end

  enum status_code: Rack::Utils::SYMBOL_TO_STATUS_CODE

  def self.by_path(path)
    all.each do |req|
      pattern = Mustermann.new(req.request_path, type: :rails)
      if pattern.match path
        return req
      end
    end
    nil
  end

  private

  def append_to_routes
    RequestRoutes.instance.add_route(self)
  end

  def route_changed?
    (changes.keys & %w(request_method request_path)).present?
  end

  def downcase_request_path_and_set_path
    request_path.downcase!
    self.request_path = '/' + request_path unless request_path.start_with?('/')
  end

  def upcase_request_method
    request_method.upcase!
  end

  def delete_request_path_end_slash
    self.request_path = request_path.chomp('/')
  end
end

app/controllers/api_requests_controller.rb
class ApiRequestsController < ApplicationController

  before_action :find_project

  def new
    @api_request = @project.api_requests.build
    @api_request.parameters.build
  end

  def show
    @api_request = @project.api_requests.find(params[:id])
  end

  def create
    @api_request = @project.api_requests.build(api_request_params)
    if @api_request.save
      redirect_to url_for(@project), notice: "#{@api_request.name} 建立成功"
    else
      render :new
    end
  end

  def edit
    @api_request = @project.api_requests.find(params[:id])
  end

  def update
    @api_request = @project.api_requests.find(params[:id])
    if @api_request.update(api_request_params)
      redirect_to url_for([@project, @api_request]), notice: "#{@api_request.name} 更新成功"
    else
      render :edit
    end
  end

  def destroy
    @api_request = @project.api_requests.find(params[:id])
    name = @api_request.name
    @api_request.destroy!
    redirect_to url_for(@project), notice: "#{name} 已經 gg 了"
  end

  private

  def api_request_params
    params.require(:api_request).permit(:name, :description, :request_method, :request_path, :return_json, :status_code, :collection_id, parameters_attributes: [:id, :name, :param_type, :required, :_destroy], headers_attributes: [:id, :key, :value, :_destroy])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/api_request_helper.rb
module ApiRequestHelper

  def request_method_to_bootstrap_class(request_method)
    case request_method
    when 'GET'
      'success'
    when 'POST'
      'primary'
    when 'PUT'
      'info'
    when 'PATCH'
      'info'
    when 'DELETE'
      'danger'
    else
      'default'
    end
  end
end

app/views/api_requests/_form.html.slim
= simple_nested_form_for [project, api_request] do |f|
  = f.input :name, label: '名稱'
  = f.input :description, label: '說明', as: :text
  = f.association :collection, label: '分類'
  = f.input :request_method, label: 'HTTP 請求方式', as: :select, collection: ApiRequest::REQUEST_METHOD.map(&:upcase), include_blank: false
  .form-inline.highlight#params
    h4 參數設定
    = render 'params_form', f: f
  = f.link_to_add '增加參數', :parameters, class: 'btn btn-info', data: { target: '#params' }
  .form-inline.highlight#headers
    h4 請求 Header 設定 <small> 請求該 API 的時候 header 中必須符合設定的 header 資訊</small>
    = render 'headers_form', f: f
  = f.link_to_add '增加header', :headers, class: 'btn btn-info', data: { target: '#headers' }
  = f.input :request_path, label: '請求路徑', wrapper: :vertical_input_group do
    .input-group-addon
      | /
    = f.input_field :request_path, class: 'form-control', value: f.object.request_path.try(:gsub, /^\//, '')

  .form-group
    .card.card-blok
      h3.card-title JSON
      #editor
        = api_request.return_json

  = f.input :return_json, as: :hidden
  = f.input :status_code, label: 'HTTP 返回狀態', as: :select, collection: ApiRequest.status_codes.keys
  = f.button :submit, '送出', class: 'btn btn-primary'

javascript:
  var editor = ace.edit('editor');
  editor.setTheme('ace/theme/monokai');
  editor.getSession().setMode('ace/mode/json');
  editor.getSession().setTabSize(2);
  editor.getSession().setUseSoftTabs(true);
  editor.getSession().on('change', function(e) {
    console.log(editor.getValue());
    $('input[id=api_request_return_json]').val(editor.getValue());
  });

app/views/api_requests/_headers_form.html.slim
= f.simple_fields_for :headers do |header|
  = header.input :key, label: false, placeholder: 'Key', input_html: { data: { source: Header::BASIC_HEADERS, behavior: 'autocomplete' } }
  = header.input :value, label: false, placeholder: 'Value'
  = header.link_to_remove do
    = fa_icon 'times'

app/views/api_requests/_params_form.html.slim
= f.simple_fields_for :parameters do |param|
  = param.input :required, label: '必填', as: :boolean
  = param.input :name, label: false, placeholder: 'Name'
  = param.input :param_type, label: false, collection: ['Text', 'File'], include_blank: false
  = param.link_to_remove do
    = fa_icon 'times'

app/views/api_requests/edit.html.slim
h2 編輯 #{@api_request.name}

= render 'api_requests/form', project: @project, api_request: @api_request

app/views/api_requests/index.html.slim
.row
  .col-md-6
    = link_to '新增', new_api_request_path, class: 'btn btn-primary pull-right'
.row
  table.table
    thead
      tr
        th Name
        th Description
        th API Method
        th API Path
        th API Return JSON
        th API Status Code
        th Action
    tbody
      - @api_requests.each do |api|
        td= api.name
        td= simple_format api.description
        td
          code= api.request_method.upcase
        td
          code= api.request_path
        td= link_to '點我看更多', url_for(api)
        td
          code= "#{Rack::Utils::SYMBOL_TO_STATUS_CODE[api.status_code.to_sym]} | #{api.status_code} "
        td= link_to '編輯', url_for([:edit, api]), class: 'btn btn-info'

app/views/api_requests/new.html.slim
h2 新增 API Request

= render 'api_requests/form', project: @project, api_request: @api_request

app/views/api_requests/show.html.slim
h2= @api_request.name

p= simple_format @api_request.description

.alert.alert-info role='alert'
  strong #{@api_request.request_method.upcase} <code> #{@project.name.downcase}#{@api_request.request_path} </code>

.col-md-12.alert.alert-warning
  pre
    code
      #json-formatter data-value="#{@api_request.return_json}"

.col-md-12
  = link_to '毀滅', url_for([@project, @api_request]), method: :delete, confirm: '你想清楚了?', class: 'btn btn-danger'

javascript:
  var json = $("#json-formatter").data('value');
  $('#json-formatter').JSONView(json);