config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :api_requests
    resources :collections
  end

  resources :settings, only: [:index, :update]

  DynamicRouter.load

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#
# Indexes
#
#  index_projects_on_slug  (slug)
#

class Project < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: [:slugged, :finders]

  has_many :api_requests, dependent: :destroy
  alias_method :apis, :api_requests
  has_many :collections

  after_commit :append_to_routes, on: :create
  after_commit :reload_routes, on: :destroy

  validates_presence_of :name

  def uncollection_apis
    apis.uncollection
  end

  def append_to_routes
    slug = self.slug

    ActionDispatch::Routing::Mapper.new(MockServer::Application.routes).instance_exec do
      match "#{slug}/*path", to: 'request_handler#handle', via: :all, defaults: { format: :json }
    end
  end

  def reload_routes
    DynamicRouter.reload
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project = Project.new
  end

  def show
    @project = Project.includes([:collections, :api_requests]).find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def index
    @projects = Project.all
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: "#{@project.name}建立成功"
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, notice: "#{@project.name} 更新成功"
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    name = @project.name
    @project.destroy!
    redirect_to projects_path, notcie: "#{name} 已經 gg"
  end


  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/views/projects/_api.html.slim
.api-content.flex-items-xs-middle
  div.flex-10.flex-container.flex-items-xs-middle
    div class="col-xs-2 tag tag-#{request_method_to_bootstrap_class(api.request_method)}"= api.request_method
    .col-xs-6.request-path= "/#{@project.name.downcase}#{api.request_path}"
    p.col-xs-4.request-description.text-xs-right.text-muted= api.description
  = link_to('Edit', url_for([:edit, @project, api]), class: 'flex-2 btn btn-info')

app/views/projects/_collection.html.slim
h3 id="collection-#{collection.id}" #{collection.name} <small class="text-muted">#{collection.description}</small>
- collection.api_requests.each do |api|
  = render 'api', api: api

app/views/projects/_form.html.slim
= simple_form_for project do |f|
  = f.input :name, label: '專案名稱(English Only)'
  = f.input :description, as: :text, label: '專案描述'
  .form-actions
    = f.button :submit, '送出', class: 'btn btn-success btn-lg'

app/views/projects/_sidebar.html.slim
ul.nav.list-group#project-sidebar
  - project.collections.each do |collection|
    li.nav-item.list-group-item
      = link_to collection.name, "#collection-#{collection.id}", class: 'nav-link'
  - if @project.uncollection_apis.count != 0
    li.nav-item.list-group-item
      = link_to '未分類', "#uncollection", class: 'nav-link'

app/views/projects/edit.html.slim
h2 編輯 #{@project.name}

= render 'projects/form', project: @project

app/views/projects/index.html.slim
.clearfix
  = link_to '新增專案', new_project_path, class: 'btn btn-primary pull-right'
table.table
  thead
    tr
      th Name
      th Description
      th Action
  tbody
    - @projects.each do |project|
      tr
        td= link_to project.name, project
        td= simple_format project.description
        td= link_to '編輯', url_for([:edit, project]), class: 'btn btn-info'

app/views/projects/new.html.slim
h2 新增專案

= render 'projects/form', project: @project

app/views/projects/show.html.slim
.row
  .col-xs-3
    = render 'sidebar', project: @project
  .col-xs-9
    h1= @project.name

    p= simple_format @project.description

    = link_to '新增分類', new_project_collection_path(@project), class: 'btn btn-success col-xs-2 offset-xs-8'
    = link_to '新增 API', new_project_api_request_path(@project), class: 'btn btn-primary col-xs-2 pull-xs-right'
    .project id="project-#{@project.id}" data-spy="scroll" data-target="#project-sidebar"
      - @project.collections.each do |collection|
        = render 'collection', collection: collection
    - if @project.uncollection_apis.count != 0
      h3#uncollection 未分類
      - @project.uncollection_apis.each do |api|
        = render 'api', api: api